name: dart_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  encrypt: ^5.0.3
  fast_rsa: ^3.6.1
  http: ^1.1.0
  pointycastle: ^3.7.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
